config/routes.rb
News::Application.routes.draw do

  match 'newsfeeds/def_json' => 'newsfeeds#def_json'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  get "/layouts/newsfeeds"  =>"newsfeeds#index"
  get "/users/show"          =>"users#show"
  resources :users
  resources :sessions
  get "/newsfeeds" => "newsfeeds#index"
  resources :newsfeeds
  resources :relationships

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :newsfeed_id, :user_id
 # belongs_to :Newsfeed
  belongs_to :User
  validates :user_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # GET /relationships
  # GET /relationships.json
  before_action :signed_in_user

  def create
    @newsfeed = User.find(params[:relationship][:newsfeed_id])
    current_user.follow!(@newsfeed)
    #redirect_to @user
    format.html { redirect_to @newsfeed }
    format.js
  end

  def destroy
    @newsfeed = Relationship.find(params[:id]).followed
    current_user.unfollow!(@newsfeed)
    #redirect_to @user
    format.html { redirect_to @newsfeed }
    format.js
  end

  def index
    @relationships = Relationship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @relationships }
    end
  end

  # GET /relationships/1
  # GET /relationships/1.json
  def show
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relationship }
    end
  end

  # GET /relationships/new
  # GET /relationships/new.json
  def new
    @relationship = Relationship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relationship }
    end
  end

  # GET /relationships/1/edit
  def edit
    @relationship = Relationship.find(params[:id])
  end

  # POST /relationships
  # POST /relationships.json
  #def create
   # @relationship = Relationship.new(params[:relationship])

    #respond_to do |format|
    #  if @relationship.save
     #   format.html { redirect_to @relationship, notice: 'Relationship was successfully created.' }
      #  format.json { render json: @relationship, status: :created, location: @relationship }
     # else
       # format.html { render action: "new" }
       # format.json { render json: @relationship.errors, status: :unprocessable_entity }
      # end
   # end
 # end

  # PUT /relationships/1
  # PUT /relationships/1.json
  def update
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      if @relationship.update_attributes(params[:relationship])
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :newsfeed_id %><br />
    <%= f.text_field :newsfeed_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h1>Editing relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<h1>Listing relationships</h1>

<table>
  <tr>
    <th>Newsfeed</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relationships.each do |relationship| %>
  <tr>
    <td><%= relationship.newsfeed_id %></td>
    <td><%= relationship.user_id %></td>
    <td><%= link_to 'Show', relationship %></td>
    <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
    <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h1>New relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Newsfeed:</b>
  <%= @relationship.newsfeed_id %>
</p>

<p>
  <b>User:</b>
  <%= @relationship.user_id %>
</p>


<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>