config/routes.rb
News::Application.routes.draw do

  match 'newsfeeds/def_json' => 'newsfeeds#def_json'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  get "/layouts/newsfeeds"  =>"newsfeeds#index"
  get "/users/show"          =>"users#show"
  resources :users
  resources :sessions
  get "/newsfeeds" => "newsfeeds#index"
  resources :newsfeeds
  resources :relationships

end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
  attr_accessor :link, :title ,:description
  attr_accessible :link, :title ,:description
      def add(new_entry)
        case new_entry
          when Hash
            @newsfeeds.merge!(new_entry)
          when String
            @newsfeeds[new_entry] = nil

        end
      end
  def new()
  require 'nokogiri'
  require 'open-uri'
  #require "http"

  doc = Nokogiri::XML(open("http://sports.yahoo.com/top/rss.xml"))

  @newsfeeds = doc.xpath('//item').map do |i|
    {'title' => i.xpath('title').inner_text,
     'link' => i.xpath('link').inner_text,
     'description' => i.xpath('description').inner_text
    }
  end
  end
  end

app/controllers/newsfeeds_controller.rb
class NewsfeedsController < ApplicationController
  attr_accessor  :link, :title ,:description
  # GET /newsfeeds
  # GET /newsfeeds.json

  def index
    require 'nokogiri'
    require 'open-uri'
    #require "http"

    doc = Nokogiri::XML(open("http://sports.yahoo.com/top/rss.xml"))

    @newsfeeds = doc.xpath('//item').map do |i|
      {'title' => i.xpath('title').inner_text,
       'link' => i.xpath('link').inner_text,
       'description' => i.xpath('description').inner_text
      }

    end
   # @newsfeeds = Newsfeed.all

#       Newsfeed.add(@newsfeeds)
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsfeeds }
      end
    p @newsfeeds
   end
  def correct_user
    @newsfeeds = current_user.newsfeed.find_by(id: params[:id])
    redirect_to root_url if @newsfeeds.nil?
  end
  # GET /newsfeeds/1
  # GET /newsfeeds/1.json
  def show
    @newsfeeds = Newsfeed.find(params[:id])

   # require 'xml/xslt'
 #xslt = XML::XSLT.new()
  # xslt.xsl = File.open('path/to/xslfile.xsl', 'r').read
   #  xslt.xml = File.open('path/to/xmlfile.xml', 'r').read
    #render_text xslt.serve()

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsfeeds }
    end
  end
  def def_json()
    require 'nokogiri'
    require 'open-uri'
    #require "http"

    doc = Nokogiri::XML(open("http://sports.yahoo.com/top/rss.xml"))

    @newsfeeds = doc.xpath('//item').map do |i|
      {'title' => i.xpath('title').inner_text,
       'link' => i.xpath('link').inner_text,
       'description' => i.xpath('description').inner_text
      }
    end
    @newsfeed.save
    puts @newsfeeds
  end

  # GET /newsfeeds/new
  # GET /newsfeeds/new.json
  def new
    @newsfeeds = Newsfeed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsfeeds }
    end
  end

  # GET /newsfeeds/1/edit
  def edit
    @newsfeeds = Newsfeed.find(params[:id])
  end
def follow()

end
  # POST /newsfeeds
  # POST /newsfeeds.json
  def create
    @newsfeeds = Newsfeed.new(params[:id])

    respond_to do |format|
      if @newsfeeds.save
        format.html { redirect_to @newsfeeds, notice: 'Newsfeed was successfully created.' }
        format.json { render json: @newsfeeds, status: :created, location: @newsfeeds }
      else
        format.html { render action: "new" }
        format.json { render json: @newsfeeds.errors, status: :unprocessable_entity }
      end
    end
  end
  # PUT /newsfeeds/1
  # PUT /newsfeeds/1.json
  def update
    @newsfeeds = Newsfeed.find(params[:id])

    respond_to do |format|
      if @newsfeeds.update_attributes(params[:links])
        format.html { redirect_to links, notice: 'Newsfeed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newsfeeds.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsfeeds/1
  # DELETE /newsfeeds/1.json
  def destroy
    @newsfeed = Newsfeed.find(params[:id])
    @newsfeed.destroy

    respond_to do |format|
      format.html { redirect_to newsfeeds_url }
      format.json { head :no_content }
    end
  end
  def create
    @newsfeed = current_user.newsfeed.build(newsfeed_params)
    if @newsfeed.save
      flash[:success] = "U r following this!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  private

  def newsfeed_params
    params.require(:newsfeed).permit(:link)
  end
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/views/newsfeeds/_follow.html.erb
<%#= form_for(current_user.relationships.build(newsfeed_id: @user.id), remote: true) do |f| %>
    <div><%#= f.hidden_field :newsfeed_id %></div>
    <div class="grid_1 alpha article-box">

      <div class="grid_4 omega">
        <h3 class="article-title"><a href="/layouts/newsfeeds">BBC News</a></h3>
        <input onclick="$(this).val('Unsubscribe');" type="button" value="Subscribe" id="blahblah_button_type" />
      </div> <%#= f.submit "Follow", class: "btn btn-large btn-primary" %>


     <!-- <input type="button" value="Subscribe" id="myButton1" onclick="changeButton();" > -->

      <div class="grid_1 alpha article-box">

        <div class="grid_4 omega">
          <h3 class="article-title"><a href="/layouts/newsfeeds">CNN IBN</a></h3>

        </div>
        <div class="clear">&nbsp;</div> </div> </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>

    <!--<p>Button tag - WORKING
      <button onclick="$(this).text('Blahblah_1');" id="test_button">Button_text (button_tag)</button>
    </p>  -->


      <input onclick="$(this).val('Subscribe');" type="button" value="Unsubscribe" id="blahblah_button_type" />




<%# end %>


app/views/newsfeeds/_follow_form.html.erb
<% unless signed_in? %>
    <div id="follow_form">
      <%# if current_user.following?(newsfeed.id) %>
          <%= render 'unfollow' %>
      <%#else %>
          <%= render 'follow' %>

    </div>
<% end %>

app/views/newsfeeds/_form.html.erb
<%= form_for(@newsfeed) do |f| %>
  <% if @newsfeed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsfeed.errors.count, "error") %> prohibited this newsfeed from being saved:</h2>

      <ul>
      <% @newsfeed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.number_field :title %>
  </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.number_field :description %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsfeeds/_unfollow.html.erb
<%= form_for(current_user.relationships.find(2),  remote: true,
             html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large" %>

<% end %>

app/views/newsfeeds/def_json.html.erb
<h1>New newsfeed</h1>
<%= form_tag newsfeeds_path do %>

<% end %>
<%= render 'form' %>

<%= link_to 'Back', newsfeeds_path %>

app/views/newsfeeds/edit.html.erb
<h1>Editing newsfeed</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsfeed %> |
<%= link_to 'Back', newsfeeds_path %>

app/views/newsfeeds/index.html.erb
<!DOCTYPE html>

<html>
<head>
  <%#= render "layouts/header" %>
  <title>News index</title>

  <table>
    <% @newsfeeds.each do |newsfeed| %>
        <!--  <div class="field">
          <%#= newsfeed["description"]%>
        </div>   -->
        <tr>

          <!--<td><%#= newsfeed["title"]%></td>    -->
          <td><a href='<%= newsfeed["link"] %>'><%= newsfeed["title"] %></a></td>

          <td><%= newsfeed["description"].html_safe %></td>
          <td><%= link_to 'Follow', newsfeed, method: :follow,data: { confirm: 'Are
you sure?' }  %></td>
          <!--<td><iframe src='<%#= render "layouts/descframe" %>'></iframe>
      <%#= newsfeed["description"] %></td>        -->


          <!--<td><#%= link_to 'Edit', edit_newsfeed_path(newsfeed) %></td>
          <td><#%= link_to 'Destroy', newsfeed, method: :delete, data: { confirm: 'Are
      you sure?' } %></td>  -->
        </tr>

    <% end %>
  </table>
  <%# flash.each do |name, msg| %>
  <%#= content_tag :div, msg, :id => "flash_#{name}" %>
  <%# end %>
</head>
<body>

<%#= yield %>

<%=yield %>
<%= render "layouts/footer" %>
</body>
</html>




<!--<h1>Welcome to Connect+ News Stream</h1>
<br>
<small><br>The most recent entries:</small><br/>


<h1>Listing newsfeeds</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Link</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>
  <ul>
    <%#= debug @newsfeeds.each.first %>
  </ul>
  <%#= @newsfeeds %>

 <!-- <tr>
      <p><#%= render(json: @newsfeeds )%></p>
    <td><#%= newsfeed.title%></td>
    <td><#%= newsfeed.link %></td>
    <td><#%= newsfeed.description %></td>
    <td><#%= link_to 'Show', newsfeed %></td>
    <td><#%= link_to 'Edit', edit_newsfeed_path(newsfeed) %></td>
    <td><#%= link_to 'Destroy', newsfeed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

</table>

<br />

<%#= link_to 'New Newsfeed', new_newsfeed_path %>

app/views/newsfeeds/new.html.erb
<h1>New newsfeed</h1>
<%= form_tag newsfeeds_path do %>

<% end %>
<%= render 'form' %>

<%= link_to 'Back', newsfeeds_path %>

app/views/newsfeeds/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Title:</b>
  <%= @newsfeed.title %>
</p>
<p>
  <b>Link:</b>
  <%= @newsfeed.link %>
</p>

<p>
  <b>Description:</b>
  <%= @newsfeed.description  %>
</p>

 <%= render_component :show => 'show' %>
<%= link_to 'Edit', edit_newsfeed_path(@newsfeed) %> |
<%= link_to 'Back', newsfeeds_path %>