config/routes.rb
News::Application.routes.draw do

  match 'newsfeeds/def_json' => 'newsfeeds#def_json'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  get "/layouts/newsfeeds"  =>"newsfeeds#index"
  get "/users/show"          =>"users#show"
  resources :users
  resources :sessions
  get "/newsfeeds" => "newsfeeds#index"
  resources :newsfeeds
  resources :relationships

end

app/views/layouts/_descframe.html.erb
<!DOCTYPE html>
<html>
<head>
  <% @newsfeeds.each do |newsfeed| %>
       <body><%= newsfeed["description"] %></body>
<% end  %>

</html>

app/views/layouts/_footer.html.erb
<h1> News Easy</h1>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News Easy header</title>
  <div id="user_nav">
    <% if signed_in? %>
       <p> Logged in as <%= current_user.email %></p>
        <%= link_to "Log out", log_out_path %>
    <% else %>
        <p>Please sign out and login again to subscribe ! </p>
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %>
    <% end %>
  </div>
</head>
<body>
</body>
</html>

app/views/layouts/_newsfeeds.html.erb
<!DOCTYPE html>

<html>
<head>
  <%= render "layouts/header" %>
  <title>News _newsfeedpage</title>

  <table>
  <% @newsfeeds.each do |newsfeed| %>
      <!--  <div class="field">
          <%#= newsfeed["description"]%>
        </div>   -->
      <tr>

    <!--<td><%#= newsfeed["title"]%></td>    -->
    <td><a href='<%= newsfeed["link"] %>'><%= newsfeed["title"] %></a></td>

        <td><%= newsfeed["description"].html_safe %></td>
        <td><%= link_to 'Follow', newsfeed, method: :follow,data: { confirm: 'Are
you sure?' }  %></td>
    <!--<td><iframe src='<%#= render "layouts/descframe" %>'></iframe>
      <%#= newsfeed["description"] %></td>        -->


    <!--<td><#%= link_to 'Edit', edit_newsfeed_path(newsfeed) %></td>
    <td><#%= link_to 'Destroy', newsfeed, method: :delete, data: { confirm: 'Are
you sure?' } %></td>  -->
  </tr>

  <% end %>
  </table>
  <%# flash.each do |name, msg| %>
      <%#= content_tag :div, msg, :id => "flash_#{name}" %>
  <%# end %>
</head>
<body>

<%#= yield %>

<%=yield %>
<%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/_newsfeedsshow.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News</title>
  <table>
  <% @newsfeeds.each do |newsfeed| %>
      <tr>

    <td><%= newsfeed["title"]%></td>
    <td><a href='<%= newsfeed["link"] %>'><%= newsfeed["link"] %></a></td>
    <td><%= newsfeed["description"] %></td>
    <td><%= link_to 'Follow', newsfeed, method: :follow,data: { confirm: 'Are
you sure?' }  %></td>
    <!--<td><#%= link_to 'Edit', edit_newsfeed_path(newsfeed) %></td>
    <td><#%= link_to 'Destroy', newsfeed, method: :delete, data: { confirm: 'Are
you sure?' } %></td>  -->
  </tr>
  <% end %>
  </table>
  <%# flash.each do |name, msg| %>
      <%#= content_tag :div, msg, :id => "flash_#{name}" %>
  <%# end %>
</head>
<body>

<%#= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News Easy</title>
<div id="user_nav">
  <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log out", log_out_path %>
  <% else %>
      <%= link_to "Sign up", sign_up_path %> or
      <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
</head>
<body>

<%=yield %>
<%#= render "layouts/header" %>
<%= render "layouts/footer" %>
    <%#=render '/layouts/newsfeedsshow'%>
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News Easy</title>
  <div id="user_nav">
    <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", log_out_path %>
    <% else %>
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
</head>
<body>

<%= yield %>

</body>
</html>